# import = [ "~/.config/alacritty/material.toml" ]
[window]
# dimensions = { columns = 80, lines = 25}
# position= {x = 2100, y = 900}
decorations = "Buttonless"
padding = { x = 2}
dynamic_padding = true

[font]

normal = { family = "Maple Mono NF CN", style = "Regular" }

bold = { family = "Maple Mono NF CN", style = "Bold" }

italic = { family = "Maple Mono NF CN", style = "Italic" }

bold_italic = { family = "Maple Mono NF CN", style = "Bold Italic" }

size = 30

[cursor]

# style = {shape = "Beam",blinking = "Off"}

