# import = [ "~/.config/alacritty/material.toml" ]
[window]
# dimensions = { columns = 65, lines = 20}
# position= {x = 2100, y = 900}
decorations = "Buttonless"
padding = { x = 2}
dynamic_padding = true

[font]

normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }

bold = { family = "MesloLGM Nerd Font Mono", style = "Bold" }

italic = { family = "MesloLGM Nerd Font Mono", style = "Italic" }

bold_italic = { family = "MesloLGM Nerd Font Mono", style = "Bold Italic" }

size = 24

[cursor]

# style = {shape = "Beam",blinking = "Off"}

