import = ["~/.config/alacritty/dracula.toml"]


[window]
dimensions = { columns = 80, lines = 40 }
# position= {x = 2100, y = 900}
decorations = "Buttonless"
# padding = { x = 2}
dynamic_padding = true
# opacity = 0.8
blur = true
option_as_alt = "Both"

[font]

normal = { family = "Maple Mono NF CN", style = "Regular" }

bold = { family = "Maple Mono NF CN", style = "Bold" }

italic = { family = "Maple Mono NF CN", style = "Italic" }

bold_italic = { family = "Maple Mono NF CN", style = "Bold Italic" }

size = 25

[cursor]

# style = {shape = "Beam",blinking = "Off"}
