

# 在提示符之间插入空行
add_newline = true


format = """
$hostname\
$os\
$character
"""

right_format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$deno\
$golang\
$nodejs\
$python\
$rust\
$solidity\
$swift\
$container\
$kubernetes\
$zig
"""
[character]
success_symbol = '[󱜙 :](bold green)'
error_symbol = '[󱚡 :](bold red)'

[hostname]
format = '[$ssh_symbol](bold blue) '
ssh_symbol = ' '

[os]
format = "[$symbol ]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[zig]
symbol = " "

[rust]
symbol = "󱘗 "

[python]
symbol = " "

[nodejs]
symbol = "󰎙 "

[golang]
symbol = " "

[docker_context]
symbol = " "

[deno]
symbol = " "

[git_branch]
symbol = " "
