theme = "onedark"

[editor]
# line-number = "relative"
mouse = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]

# display-messages = true

[keys.insert]
j = { k = "normal_mode"}

[keys.normal]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
